title: Title
url: https://aic.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#f05123"
  secondary-color: "#f59c00"
  media-colors:
    - title: media-color-one
      color: "#fbb800"
    - title: media-color-two
      color: "#e6e000"
    - title: media-color-three
      color: "#74a0cc"
    - title: media-color-four
      color: "#74a0cc"
    - title: media-color-five
      color: "#74a0cc"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dd55qlc8vam5u.amplifyapp.com
prod: https://master.dd55qlc8vam5u.amplifyapp.com
facebook-pixel: ""
shareicon: /images/favicon-isomer.ico
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
